### ISSUE TITLE
Tweak yo dev env with some changes

### ISSUE THREAD

**Issue by jlyon** [proudcity/proud#58]
Make these changes to your folder structure (or create new terra env): https://github.com/proudcity/proud-terra-dev/commit/2e435ecb0148608072481d4dba60e5130f476aeb

Waiting on https://www.drupal.org/node/2581555, but the url for proud_panels will change.

enable proud_panels
```
drush en -y proud_panels
```

**Comment by jlyon** [comment]
switch out proud_panels to http://git.drupal.org/project/proud_panels.git

**Comment by jlyon** [comment]
Update proud branch: git clone --branch 7.x-1.x https://github.com/proudcity/proud.git

**Comment by aschmoe** [comment]
Hey so whats the branch plan here?

**Comment by jlyon** [comment]
Just normal Drupal.org 7.x-1.x stuff if we need it, otherwise master. I
forgot to setup the 7.x branch on the proud repo initially

**Comment by aschmoe** [comment]
Hey so I'm gonna keep closing this so it doesn't get overlooked.... just keep on openin' if needs be
