### ISSUE TITLE
Merge proud_panels, proud_widgets?

### ISSUE THREAD

**Issue by jlyon** [proudcity/proud#61]
Or maybe make proud_widgets a submodule?  Or maybe keep them totally separate but move in some of the Panels Add display logic from proud_widgets to proud_panels? 

I think I'm leaning towards option 3, making proud_widgets the featurized FPPs, and proud_panels the place where Panels styles, layouts, content, and hook_ hacks happen.

Thoughts @aschmoe ?

**Comment by aschmoe** [comment]
Yeah think thats fine, I guess my first inclination would be 

proud_panels - layouts, settings, hooks
proud_panels_widgets - FPP only 

But it doesn't matter

**Comment by aschmoe** [comment]
Sorry thats basically what you said.  Misread it slightly

**Comment by jlyon** [comment]
done
